In [3]:
import plotly.express as px
import numpy as np
import pandas as pd
import seaborn as sns

In [4]:
df=sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

## 1. Scatter Plot

In [ ]:
fig1=px.scatter(df,x='sepal_length',y='sepal_width',color='species')
fig1.show()

## 2. Line Chart

In [11]:
# sort the data

df_line = df.sort_values(by=['sepal_length'])
fig2=px.line(df_line,x='sepal_length',y='sepal_width',color='species')
fig2.show()

## 3. Bar Chart

In [13]:
df_bar=df.groupby(['species']).mean().reset_index()
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [14]:
fig3=px.bar(df_bar,x='sepal_length',y='sepal_width')
fig3.show()

## 4.Box Plot

In [16]:
fig4=px.box(df,x='species',y='sepal_width',color='species')
fig4.show()

## 5. Violen Plot

In [19]:
fig5=px.violin(df,x='species',y='sepal_width',color='species')
fig5.show()

In [20]:
fig5=px.violin(df,x='species',y='sepal_width',color='species',box=True)
fig5.show()

## 6. Histogram

In [21]:
fig6=px.histogram(df,x='sepal_width')
fig6.show()